version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    container_name: teknav-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tek_user
      POSTGRES_PASSWORD: tek_pass
      POSTGRES_DB: teknav
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
